---
- hosts: network
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=config/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: copy Quagga daemons
      copy: src=config/daemons dest=/etc/quagga/
      
- hosts: spine
  become: yes
  tasks:
    - name: copy Quagga conf
      copy: src=config/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/
    - name: reload networking
      command: ifreload -a
    - name: reload quagga
      service: name=quagga state=restarted
      

- hosts: leaf
  become: yes
  tasks:
    - name: reload networking
      command: ifreload -a
    - name: reload quagga
      service: name=quagga state=restarted
    - name: start redistribute neighbor
      command: systemctl enable rdnbrd.service
    - name: restart redistribute neighbor
      command: systemctl restart rdnbrd.service
    - name: copy Quagga conf
      copy: src=config/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/
    - name: reload networking
      command: ifreload -a
    - name: reload quagga
      service: name=quagga state=restarted

- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - install-docker-ifupdown2
    - copy-interfaces-dockerfile-restart
    
- hosts: server01
  user: cumulus
  become: yes
  become_method: sudo
  tasks:
    - name: create docker macvlan network
      docker_network:
        name: "{{ansible_hostname}}"_eth1
        driver: macvlan
        driver_options:
          parent: eth1
        ipam_options: 
          subnet: 172.16.1.0/24
          gateway: 172.16.1.1
          iprange: 172.16.1.0/24
    - name: build container
      command: docker build -t test_container /home/cumulus/
    - name: run container 1
      command: docker run --ip=172.16.1.11 --net=server01_eth1 -itd test_container
    - name: run container 2
      command: docker run --ip=172.16.1.12 --net=server01_eth1 -itd test_container
    - name: run container 3
      command: docker run --ip=172.16.1.13 --net=server01_eth1 -itd test_container
      
      
- hosts: server02
  user: cumulus
  become: yes
  become_method: sudo
  tasks:
    - name: create docker macvlan network
      docker_network:
        name: "{{ansible_hostname}}"_eth2
        driver: macvlan
        driver_options:
          parent: eth2
        ipam_options: 
          subnet: 172.16.1.0/24
          gateway: 172.16.1.1
          iprange: 172.16.1.0/24

    
    - name: build container
      command: docker build -t test_container  /home/cumulus/
    - name: run container 1
      command: docker run --ip=172.16.1.21 --net=macnetworketh2 -itd test_container
    - name: run container 2
      command: docker run --ip=172.16.1.22 --net=macnetworketh2 -itd test_container
    - name: run container 3
      command: docker run --ip=172.16.1.23 --net=macnetworketh2 -itd test_container

- hosts: server03
  become: yes
  tasks:
    - name: create docker macvlan network
      docker_network:
        name: "{{ansible_hostname}}"_eth1
        driver: macvlan
        driver_options:
          parent: eth1
        ipam_options: 
          subnet: 172.16.1.0/24
          gateway: 172.16.1.1
          iprange: 172.16.1.0/24
          
          
    - name: build container
      command: docker build -t test_container /home/cumulus/
    - name: run container 1
      command: docker run --ip=172.16.1.31 --net=macnetworketh1 -itd test_container
    - name: run container 2
      command: docker run --ip=172.16.1.32 --net=macnetworketh1 -itd test_container
    - name: run container 3
      command: docker run --ip=172.16.1.33 --net=macnetworketh1 -itd test_container
      
- hosts: server04
  become: yes
  tasks:
   - name: create docker macvlan network
      docker_network:
        name: "{{ansible_hostname}}"_eth2
        driver: macvlan
        driver_options:
          parent: eth2
        ipam_options: 
          subnet: 172.16.1.0/24
          gateway: 172.16.1.1
          iprange: 172.16.1.0/24

      
    - name: build container
      command: docker build -t test_container  /home/cumulus/
    - name: run container 1
      command: docker run --ip=172.16.1.41 --net=macnetworketh2 -itd test_container
    - name: run container 2
      command: docker run --ip=172.16.1.42 --net=macnetworketh2 -itd test_container
    - name: run container 3
      command: docker run --ip=172.16.1.43 --net=macnetworketh2 -itd test_container
     

